services:
  postgres:
    container_name: postgres
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_DB: 'eselink'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123456'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning", "--requirepass", "123456"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
